### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by alpha-and-omega** [blemasle/gpstracker-firmware#1]
Hello Bertrand.
Thank you for this great project!
Do you have plans to implement it with 4g capable sim7000 series chip ? If you do, I can help you with that.
And to make it even better - accelerometer driven low power control - to make this tracker live not weeks but multiple years on batteries.
Check out industrial Yabby gps battery powered tracker with 3 years! of battery life, but closed source and requires expensive subscription...
I also would like to see smaller footprint, is it possible ?

**Comment by blemasle** [comment]
Hi @alpha-and-omega ,
Thank you :)
I do not have plans to work on this project at the moment sorry. I would have love to incorporate an accelerometer to save battery power. Sadly, I had to design and test the PCB in a few weeks and choosed and the extra power was a "nice to have" given my use case.

I cannot allow time to this project at the moment, but you're more than welcome to fork the [PCB repository](https://github.com/blemasle/gpstracker-pcb) and creates your own from PCB that :)

I do not know the sim7000 chip but I'm quite sure you can easily replace the SIM808 with it. You can also save a great amont of space by going on a full dual side PCB (and remove the SDCard which I'm not using in the end because I ran out of flash memory).

Regards
